name: 'BrowserStack Tests'
on: [push]
jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup' # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'BrowserStack Local Tunnel Setup' # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      # The next 3 steps are for building the application to be tested and starting the tests
      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Building the application to be tested'
        run: npm ci

      - name: 'Running test on BrowserStack' # Invokes the actual test script that would run on BrowserStack browsers
        env:
          BROWSERSTACK_ANDROID_APP_ID: ${{ secrets.BROWSERSTACK_ANDROID_APP_ID }} #letting know the browserstack to run the app we uploaded before
        run: npm run test:android:bs

      - name: 'BrowserStackLocal Stop' # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
